rails6-compose/apps/baukis2/config/routes.rb
Rails.application.routes.draw do
  config = Rails.application.config.baukis2
  # ¥ 下記は実験 コメントアウト 名前空間なし ver.
  # root "temporary#index"

  # puts("config[:admin][:host]:: #{config[:admin][:host]}")
  # puts("config[:staff][:host]:: #{config[:staff][:host]}")
  # puts("config[:staff][:path]:: #{config[:staff][:path]}")
  puts(Rails.application.config.hosts)

  # constraints host: "example.com" do
  #   get "login" => "staff/sessions#new", as: :login
  # end

  # get "login" => "staff/sessions#new", as: :login

  # namespace  :staff do
  # ¥ /staff/login から /login に変わる path ""でurlのpathを変えたため 20230724
  # ¥ ホスト名によるルーティング制限 20230725
  # constraints host: "baukis2.example.com" do
  constraints host: config[:staff][:host] do
    # namespace :staff, path: "" do
    namespace :staff, path: config[:staff][:path] do
      root "top#index"
      get "login" => "sessions#new", as: :login
      # post "sessions" => "sessions#create", as: :session
      # delete "sessions" => "sessions#destroy"
      #¥ 上記をresourceで書き換えることが可能! 20230724
      resource :session, only: [ :create, :destroy]

      # ¥ 単数リソース 自分自身の情報を変更したり参照したりする 20230724
      #  ! コントローラ名はstaff/accounts(複数形)になる!!
      # resource :account, except: [ :new, :create, :destroy]
      # ¥ 2.ch.9 章末問題
      resource :account, except: [ :new, :create, :destroy ] do
        patch :confirm
      end
      resource :password, only: [ :show, :edit, :update] # 20230809
      resources :customers
      # resources :programs
      # ¥ 2.ch.7.3.2
      # - programs リソースを定義する resources メソッドにブロックを加え、ブロックの中でリソース entries を定義しています。本編Chapter 13で解説した「ネストされたリソース」です。ただし、リソース entries を定義する resources メソッドの only オプションに空の配列が渡されているため、基本の7アクションは設定されません。その代わりに、PATCHでアクセスするための update_all アクションが設定されています。 この update_all アクションは、単独の Entry オブジェクトを書き換えるものではなく、複数個の Entry オブジェクトを一括更新します。そのため、 on オプションに :collection が指定されています。つまり、 update_all アクションには対象オブジェクトを特定するためのパラメータ "id" が渡りません。
      resources :programs do
        resources :entries, only: [] do
          patch :update_all, on: :collection
        end
      end
      # ¥ 2.ch.10.2.1 問い合わせ到着の通知
      # messages/count というパスへのアクセスを Staff::AjaxController コントローラに振り向けています。このコントローラ名は、Railsの標準的な命名法から外れています。このコントローラはAjaxリクエスト専用のアクションが集められる特別なものなので、特別な名前を与えることにしました
      get "messages/count" => "ajax#message_count"
      # ¥ 2.ch.12.2.5 タグ付け - タグの追加・削除
      # * POSTメソッドとDELETEメソッドの両方に対応したアクションのためのルーティングを定義しています。タグの追加・削除は後ほどAjaxにより実装するので、コントローラにはStaff::AjaxControllerを指定しています。また、問い合わせのデータベースレコードを特定できるようにURLパターンに:idを含めている点にも注意をしてください。
      post "messages/:id/tag" => "ajax#add_tag", as: :tag_message
      delete "messages/:id/tag" => "ajax#remove_tag"

      # ¥ 2.ch.11.1.1 ツリー構造
      #- inbound、 outbound、 deleted は、それぞれ「問い合わせ一覧」、「送信一覧」、「ゴミ箱」を表示するためのアクションです。いずれの場合も複数のデータベースレコードへのアクセスが発生するため、コレクションルーティングとして設定しています
      # * これらはコレクションルートなので、メンバールートのように:idパラメータを必要としません。
      resources :messages, only: [ :index, :show, :destroy ] do
        get :inbound, :outbound, :deleted, on: :collection

        # ¥ 2.ch.12.1.1 タグ付け
        resource :reply, only: [ :new, :create] do
          post :confirm
        end
      end
      # ¥ 2.ch.12.3.2 タグ付け
      # staff/tagsリソースにネストされたmessagesリソースを定義しています。コントローラは既存のstaff/messagesを利用します。
      resources :tags, only: [] do
        resources :messages, only: [ :index ] do
          get :inbound, :outbound, :deleted, on: :collection
        end
      end
    end
  end

  constraints host: config[:admin][:host] do
    #  namespaceで :admin となっているため path: を設定しなくてもurlに /admin はつく
    namespace  :admin, path: config[:admin][:path] do
      root "top#index"
      get "login" => "sessions#new", as: :login
      # post "sessions" => "sessions#create", as: :session
      # delete "sessions" => "sessions#destroy"
      #¥ 上記をresourceで書き換えることが可能! 20230724
      resource :session, only: [ :create, :destroy]

      # get "staff_members" => "staff_members#index" # リスト表示
      # get "staff_members/:id" => "staff_members#show" # 詳細表示
      # get "staff_members/new" => "staff_members#new" # 登録フォームの作成
      # get "staff_members/:id/edit" => "staff_members#edit" # 編集フォームの表示
      # post "staff_members" => "staff_members#create" # 職員の追加
      # patch "staff_members/:id" => "staff_members#update" # 職員の更新
      # delete "staff_members/:id" => "staff_members#destroy" # 職員の削除

      # ¥ 上記を1行で書ける
      # ! 20230805 :staff_members が コントロール名となる
      # ! 20230805 railsが自動で ルート名を作成する rails routes で確認できる
      # resources :staff_members
      # ¥ 20230806 ネストされたリソース
      #  - ルーティング結果:
      # - admin_staff_member_staff_events GET    /admin/staff_members/:staff_member_id/staff_events(.:format)    admin/staff_events#index {:host=>"baukis2.example.com"}
      resources :staff_members do
        resources :staff_events, only: [:index]
      end
      resources :staff_events, only: [:index]
      # ¥ 2.ch5.2.2 許可IPアドレスの管理
      # - on: :collection： このルートがコレクションルートであることを指定します。コレクションルートはリソースのコレクション（この場合は allowed_sources）に作用します。単一のリソースに作用しないため、ルートはIDを必要としません。生成されるURLは/allowed_sources/deleteになります。
      resources :allowed_sources, only: [:index, :create] do
        delete :delete, on: :collection
      end

      # -ルーティング結果: GET /admin/staff_events  | ルーティング名: :admin_staff_events
    end # end of namespace
  end

  # baukis2/config/initializers/baukis2.rb  ->  customer: { host: "example.com", path: "mypage" }
  constraints host: config[:customer][:host] do
    namespace  :customer, path: config[:customer][:path] do
      root "top#index"
      get "login" => "sessions#new", as: :login
      resource :session, only: [:create, :destroy]
      # ¥ 2.ch.9.1.1 顧客自身によるアカウント管理機能
      # resource :account, except: [ :new, :create, :destroy]
      # ¥ 2.ch.9.2.1 顧客自身によるアカウント管理機能
      resource :account, except: [ :new, :create, :destroy] do
        # * confirm アクションを追加(PATCHメソッドでアクセス)
        patch :confirm
      end

      # ¥ 2.ch.8.1.1 プログラム一覧表示・詳細表示機能(顧客向け)
      # resources :programs, only: [ :index, :show]
      # ¥ 2.ch.8.2.2 プログラム一覧表示・詳細表示機能(顧客向け)
      resources :programs, only: [ :index, :show] do
        # - リソース programs にネストされた単数リソース entry を定義しています。顧客とプログラムが特定された文脈において、それらと関連付けられた Entry オブジェクトは0個または1個しか存在しないので、 id パラメータなしで取得できます。そのため単数リソースとして定義します。
        resource :entry, only: [ :create ] do
          patch :cancel
          # - 上記の httpメソッドとurlパスのパターン
          # create - POST /customer/programs/:program_id/entry
          # cancel - PATCH /customer/programs/:program_id/entry/cancel
        end
      end
      # ¥ 2.ch.10.1.5 Ajax 顧客向け問い合わせフォーム
      # - confirm という3つのアクションを追加します。顧客アカウント編集用の確認画面を実装した9-2-1項「ルーティング」では、既にデータベース上に存在するレコードを書き換える処理だったため、確認用のアクション confirm をPATCHメソッドで呼ぶことにしました。一方、今回は新しいレコードを追加する処理のため、 confirm アクションをPOSTメソッドで呼んでいます。また、 confirm アクションは resources メソッドにネストされているため、コレクションルーティング（本編9-2-2「ルーティングの分類」参照）として指定をする必要があります。なぜなら、この指定をしない場合のURLパスは/mypage/messages/:message_id/confirm となり、不必要なパラメータ message_id が含まれてしまうからです
      # resources :messages, only: [ :new, :create] do
      # ¥ 2.ch.12.5演習問題
      # resources :messages, only: [ :index, :show, :new, :create] do
      # ¥ 2.ch.12.5演習問題 3
      resources :messages, except: [ :edit, :update] do
        post :confirm, on: :collection
        resource :reply, only: [ :new, :create] do
          post :confirm
        end
      end
    end
  end
end

# ¥ 4行目と5行目の末尾にある as オプションは、ルーティングに名前を付けるためのものです。こうしておけば、ERBテンプレートの中で:staff_login や:staff_session というシンボルを用いてURLパスを参照できるようになります。Baukis2では、設定ファイルによってURLパスが変化しますので、ルーティングへの名前付けは必須

rails6-compose/apps/baukis2/app/controllers/customer/messages_controller.rb
# class Customer::MessagesController < ApplicationController
class Customer::MessagesController < Customer::Base
  # ¥ 2.ch.12.5演習問題
  def index
    @messages = current_customer.inbound_messages.sorted.page(params[:page])
  end

  # ¥ 2.ch.12.5演習問題
  def show
    @message = current_customer.inbound_messages.find(params[:id])
  end

  def new
    @message = CustomerMessage.new
  end

  # ¥ 2.ch.10.1.7 Ajax 顧客向け問い合わせフォーム
  # POST
  def confirm
    @message = CustomerMessage.new(customer_message_params)
    @message.customer = current_customer
    if @message.valid?
      render action: "confirm"
    else
      flash.now.alert = "入力に誤りがあります。"
      render action: "new"
    end
  end

  # ¥ 2.ch.10.1.7 Ajax 顧客向け問い合わせフォーム
  def create
    @message = CustomerMessage.new(customer_message_params)
    # * フォームビルダーの submit メソッドには name オプションを与えることができます。これは input 要素の name 属性の値として用いられます。 name オプションのデフォルト値が "commit" です。フォームが送信されると、クリックされたボタンの name 属性をキーとするパラメータも同時に送信されます。つまり、「送信」ボタンがクリックされると "commit" というキーのパラメータが、「訂正」ボタンがクリックされると、"correct" というキーのパラメータが update アクションに渡ります。 したがって、 params[:commit] に値がセットされているかどうかで、どちらのボタンが押されたのかが判定できるというわけです
    if params[:commit]
      @message.customer = current_customer
      if @message.save
        flash.notice = "問い合わせを送信しました。"
        redirect_to :customer_root
      else
        flash.now.alert = "入力に誤りがあります。"
        render action: "new"
      end
    else
      render action: "new"
    end
  end

  private def customer_message_params
    params.require(:customer_message).permit(:subject, :body)
  end

  # ¥ 2.ch.12.5演習問題 3
  def destroy
    message = current_customer.inbound_messages.find(params[:id])
    message.update_column(:discarded, true)
    flash.notice = "メッセージを削除しました。"
    redirect_back(fallback_location: :customer_message)
  end
end

rails6-compose/apps/baukis2/app/controllers/staff/accounts_controller.rb
# class Staff::AccountsController < ApplicationController
class Staff::AccountsController < Staff::Base
  def show
    @staff_member = current_staff_member
  end

  def edit
    @staff_member = current_staff_member
  end

  # ¥ 2.ch.9 章末問題
  # PATCH
  def confirm
    @staff_member = current_staff_member
    @staff_member.assign_attributes(staff_member_params)
    if @staff_member.valid?
      render action: "confirm"
    else
      render action: "edit"
    end
  end

  def update
    @staff_member = current_staff_member
    # if @staff_member.update_attributes(params[:staff_@staff_member])
    #   flash[:success] = "StaffMember was successfully updated"
    #   redirect_to @staff_member
    # else
    #   flash[:error] = "Something went wrong"
    #   render 'edit'
    # end

    # @staff_member.assign_attributes(params[:staff_member])
    @staff_member.assign_attributes(staff_member_params)
    # if @staff_member.save
    #   flash.notice = "アカウント情報を更新しました。"
    #   redirect_to :staff_account
    # else
    #   render action: "edit"
    # end
    # ¥ 2.ch.9 章末問題
    if params[:commit]
      if @staff_member.save
        flash.notice = "アカウント情報を更新しました。"
        redirect_to :staff_account
      else
        render action: "edit"
      end
    else
      render action: "edit"
    end
  end

  # ¥ 20230805 マスアサインメント脆弱性対策 Strong Parametersによる防御
  private def staff_member_params
    params.require(:staff_member).permit(:email, :family_name, :given_name, :family_name_kana, :given_name_kana)
  end

  # ! 20230805 private メソッド staff_member_params についても、 admin/staff_members コントローラの同名メソッドとほぼ同じですが、 permit メソッドに指定されている属性のリストが異なります。管理者が職員アカウントを更新する際には、開始日（ start_date）、終了日（ end_date）、停止フラグ（ suspended）も変更可能でしたが、これらの属性については職員自身によって変えられないようにしてあります。

  # !また、パスワード（ password）もリストから除いてあります。パスワードの変更機能はChapter 15で作成します。 この章の前半で書いたことの繰り返しになりますが、たとえブラウザ上のフォームに変更可能な属性のためのフィールドしか表示されていないとしても、Strong Parametersによる防御機構がなければ、職員が簡単なスクリプトを書いて自分自身の終了日や停止フラグを変更できることになります。それは重大なセキュリティホールとなる可能性があります


end

rails6-compose/apps/baukis2/app/controllers/staff/ajax_controller.rb
# ¥ 2.ch.10.2.2 問い合わせ到着の通知 ajax
# - 本書におけるこれまでのコントローラの作り方と異なり、 Staff::AjaxController は Staff::Base ではなく、 ApplicationController を継承しています。なぜでしょうか。それは、ブラウザがこのコントローラのアクションを呼び出す権限がないときに、サーバーが返すべきレスポンスが異なるからです
class Staff::AjaxController < ApplicationController
  before_action :check_source_ip_address
  before_action :authorize
  before_action :check_timeout
  # ¥ 2.ch.10.2.5 問い合わせ到着の通知 ajax
  before_action :reject_non_xhr # - application_controllerから呼び出す

  # GET
  def message_count
    render plain: CustomerMessage.unprocessed.count
  end

  # ¥ 2.ch.12.2.5 タグ付け - タグの追加・削除
  # POST
  def add_tag
    message = Message.find(params[:id])
    message.add_tag(params[:label])
    render plain: "ok"
  end

  # ¥ 2.ch.12.2.5 タグ付け - タグの追加・削除
  # DELETE
  def remove_tag
    message = Message.find(params[:id])
    message.remove_tag(params[:label])
    render plain: "ok"
  end

  private def check_source_ip_address
    unless AllowedSource.include?("staff", request.ip)
      render plain: "Forbidden", status: 403
    end
  end

  private def current_staff_member
    if session[:staff_member_id]
      StaffMember.find_by(id: session[:staff_member_id])
    end
  end

  private def authorize
    unless current_staff_member && current_staff_member.active?
      render plain: "Forbidden", status: 403
    end
  end

  private def check_timeout
    unless session[:last_access_time] &&
           session[:last_access_time] >= Staff::Base::TIMEOUT.ago
      session.delete(:staff_member_id)
      render plain: "Forbidden", status: 403
    end
  end
end

rails6-compose/apps/baukis2/app/controllers/staff/base.rb
class Staff::Base < ApplicationController
  # ¥ 2.ch5.1.4 ipアドレスによるアクセス制限
  before_action :check_source_ip_address
  before_action :authorize
  before_action :check_account
  before_action :check_timeout # 20230806

  private def current_staff_member
    # - sessions_controller.rbで取得: session[:staff_member_id] = staff_member.id
    if session[:staff_member_id]
      #¥ Rubyの||=演算子は、しばしば「or equals」演算子と呼ばれる。これは、ある変数が現在nilかfalseである場合にのみ、その変数をある値に設定するために使われます。 20230723
      @current_staff_member ||= StaffMember.find_by(id: session[:staff_member_id])
    end
  end

  helper_method :current_staff_member

  private def check_source_ip_address
    raise IpAddressRejected unless AllowedSource.include?("staff", request.ip)
  end

  private def authorize
    unless current_staff_member
      flash.alert = "職員としてログインしてください。"
      redirect_to :staff_login
    end
  end

  # ¥ 20230806 強制ログアウト機能
  private def check_account
    # ¥ baukis2/app/models/staff_member.rb のモデル内で設定した .active? メソッドを使うことができる!
    # ^ @current_staff_member ||= StaffMember.find_by(id: session[:staff_member_id]) は StaffMemberクラスを継承しているため 20230806
    if current_staff_member && !current_staff_member.active?
      session.delete(:staff_member_id)
      flash.alert = "アカウントが無効になりました。"
      redirect_to :staff_root
    end
  end

  # ¥ 20230806 セッションタイムアウト処理
  # 整数60に対して minutes メソッドを呼び出すと、「3600秒」に相当する ActiveSupport::Duration オブジェクトが返ってくる
  TIMEOUT = 60.minutes
  # TIMEOUT = 5.seconds #検証用

  private def check_timeout
    if current_staff_member
      # ! app/controllers/staff/sessions_controller.rb で session[:last_access_time] = Time.current として定義しているため使用可能
      if session[:last_access_time] >= TIMEOUT.ago # 現在時刻から TIMEOUT分(3600秒)遡った時間を取得
        session[:last_access_time] = Time.current # 最終アクセス時刻を更新
      else
        session.delete(:staff_member_id)
        flash.alert = "セッションがタイムアウトしました。 email: taro@example.com / pass: password でログイン可能"
        redirect_to :staff_login
      end
    end
  end

end

#¥ 7.3.2　 current_staff_memberメソッドの定義 名前空間 staff に属するすべてのコントローラに current_staff_member という private メソッドを与えるため、 Staff::Base というクラスを定義します。 app/controllers/staff ディレクトリに新規ファイル base.rb を次のような内容で作成してください。

#¥ base.rb の9行目にある helper_method は引数に指定したシンボルと同名のメソッドをヘルパーメソッドとして登録するメソッドです。つまり、 current_staff_member というメソッドを app/helpers/application_helper.rb に定義するのと同じ効果が得られます。この結果、 current_staff_member メソッドをERBテンプレートの中でも利用することが可能となります。

# これらの変更を行った結果、 Staff::TopController の継承関係が次のように変わります。
# 変更前 …… Staff::TopController ← ApplicationController
# 変更後 …… Staff::TopController ← Staff::Base ← ApplicationController

#! 遅延初期化
# current_staff_member は、現在ログインしている StaffMember オブジェクトを返すメソッドです。このメソッドでは 遅延初期化 というテクニックを用いています。 current_staff_member メソッドが初めて呼ばれたとき、インスタンス変数@current_staff_member の中身は nil であるため、演算子 ||= の右辺が評価されて@current_staff_member にセットされます。そして、このメソッドが2回目以降に呼び出されたときは、@current_staff_member に nil でも false でもない値がセットされているので、演算子 ||= の右辺は評価されずに、そのまま@current_staff_member の値が返されます。

# このようにすることで、 StaffMember.find_by メソッドが多くても1回しか呼ばれないようにしています。これを遅延初期化と呼びます。 3行目で使われている session は セッションオブジェクト を返すメソッドです。セッションオブジェクトはRailsアプリケーションがクライアントごとに保持するデータで、普通のハッシュ同様に読み書きできます。このオブジェクトに:staff_member_id というキーがあれば、その値を用いて StaffMember を検索して@current_staff_member にセットします。

rails6-compose/apps/baukis2/app/controllers/staff/entries_controller.rb
# ¥ 2.ch.7.3.3 多数のオブジェクトの一括更新処理
# class Staff::EntriesController < ApplicationController
class Staff::EntriesController < Staff::Base
  def update_all
    entries_form = Staff::EntriesForm.new(Program.find(params[:program_id]))
    entries_form.update_all(params)
    flash.notice = "プログラム申し込みのフラグを更新しました。"
    redirect_to :staff_programs
  end
end

rails6-compose/apps/baukis2/app/helpers/staff_helper.rb
# ¥ 2.ch.10.2.2 問い合わせ到着の通知 ajax
module StaffHelper
  include HtmlBuilder

  # - .unprocessed は customer_message.rb で作った scope名
  def number_of_unprocessed_messages
    markup do |m|
      # m.a(href: "#") do
      # - ¥ 2.ch.11.1.2 ツリー構造
      m.a(href: inbound_staff_messages_path) do
        m << "新規問い合わせ"
        anchor_text =
          if (c = CustomerMessage.unprocessed.count) > 0
            "(#{c})"
          else
            ""
          end
        m.span(
          anchor_text,
          id: "number-of-unprocessed-messages",
          "data-path" => staff_messages_count_path
        )
      end
    end
  end
end

#- in routes.rbの中で namespace :staff / get "messages/count" => "ajax#message_count" としているので "data-path" => staff_messages_count_path　というhelper method(staff_messages_count_path)を使える

rails6-compose/apps/baukis2/app/views/staff/messages/_links.html.erb
<%# ¥ 2.ch.12.3.4 タグ付け %>
<div class="links">
  <%= link_to "問い合わせ一覧", :inbound_staff_messages %>
  <%= link_to "返信一覧", :outbound_staff_messages %>
  <%= link_to "全メッセージ一覧", :staff_messages %>
  <%= link_to "ゴミ箱", :deleted_staff_messages %>
  <% if @message.kind_of?(CustomerMessage) %>
    <%= link_to "返信する", new_staff_message_reply_path(@message) %>
  <% end %>
</div>

rails6-compose/apps/baukis2/app/views/staff/messages/_tags.html.erb
<%# ¥ 2.ch.12.3.3 タグ付け %>
<%
=begin
%>

<div class="tags">
  タグ：
  <% Tag.all.each do |tag| %>
    <% if tag.id == params[:tag_id].to_i %>
      <span class="current_tag"><%= tag.value %></span>
    <% else %>
      <%= link_to tag.value, [ :staff, tag, :messages ] %>
    <% end %>
  <% end %>
</div>

<%
=end
%>
<%# ¥ 2.ch.12.3.5 タグ付け - 引数を取るスコープ %>
<div class="tags">
  タグ：
  <% Tag.all.each do |tag| %>
    <% if tag.id == params[:tag_id].to_i %>
      <span class="current_tag"><%= tag.value %></span>
    <% elsif params[:action] == "index" %>
      <%#- resourcesのオリジナルの動きで :index は この場合、url上で messagesになる %>
      <%# url: http://baukis2.example.com:3000/messages %>
      <%# タグクリック後url: http://baukis2.example.com:3000/tags/1/messages %>
      <%= link_to tag.value, [ :staff, tag, :messages ] %>
    <% else %>
      <%# url:http://baukis2.example.com:3000/messages/inbound %>
      <%# タグクリック後url: http://baukis2.example.com:3000/tags/1/messages/inbound %>
      <%= link_to tag.value, [ params[:action].to_sym, :staff, tag, :messages ] %>
    <% end %>
  <% end %>
</div>

<div>params[:action]: <%= params[:action] %></div>

rails6-compose/apps/baukis2/app/views/staff/messages/index.html.erb
<%# ¥ 2.ch.11.1.3 ツリー構造 %>
<%#  - messages_controller.rbより、下記のように render action: "index" としているため、index.html.erbを共有している

  def index
    # * message.rb の scopeを使用している
    @messages = Message.not_deleted.sorted.page(params[:page])
  end

  # GET
  def inbound
    @messages = CustomerMessage.not_deleted.sorted.page(params[:page])
    render action: "index"
  end

  # GET
  def outbound
    @messages = StaffMessage.not_deleted.sorted.page(params[:page])
    render action: "index"
  end

  # GET
  def deleted
    @messages = Message.deleted.sorted.page(params[:page])
    render action: "index"
  end %>
  <%# ^ case params[:action] でaction毎に表示メッセージを変更している %>
<%
@title =
  case params[:action]
  when "index"; "全メッセージ一覧"
  when "inbound"; "問い合わせ一覧"
  when "outbound"; "返信一覧"
  when "deleted"; "メッセージ一覧（ゴミ箱）"
  else; raise
  end
%>
<h1><%= @title %></h1>

<div class="table-wrapper">
  <%# ¥ 2.ch.12.3.4 タグ付け %>
  <%= render "links" %>

  <%= paginate @messages %>

  <table class="listing">
    <tr>
      <th>種類</th>
      <th>送信者</th>
      <th>受信者</th>
      <th>件名</th>
      <th>作成日時</th>
      <th>アクション</th>
    </tr>
    <% @messages.each do |m| %>
      <% p = MessagePresenter.new(m, self) %>
      <tr>
        <td><%= p.type %></td>
        <td><%= p.sender %></td>
        <td><%= p.receiver %></td>
        <td><%= p.truncated_subject %></td>
        <td><%= p.created_at %></td>
        <td class="actions">
          <%= link_to "詳細", staff_message_path(m) %> |
          <%= link_to_if m.kind_of?(CustomerMessage), "削除",
            staff_message_path(m), method: :delete %>
        </td>
      </tr>
    <% end %>
  </table>

  <%= paginate @messages %>

  <%# ¥ 2.ch.12.3.3 タグ付け %>
  <%= render "tags" %>
</div>

rails6-compose/apps/baukis2/app/views/staff/messages/show.html.erb
<%# ¥ ¥ 2.ch.11.2.1 ツリー構造 %>
<% @title = "メッセージ詳細" %>
<h1><%= @title %></h1>

<div class="table-wrapper">
<%# ¥ 2.ch.12.1.2 タグ付け %>
<%
=begin
%>

<% if @message.kind_of?(CustomerMessage) %>
  <div class="links">
    <%= link_to "返信する", new_staff_message_reply_path(@message) %>
  </div>
<% end %>

<%
=end
%>
  <%# ¥ 2.ch.12.3.4 タグ付け %>
  <%= render "links" %>

  <table class="attributes">
    <% p = MessagePresenter.new(@message, self) %>
    <tr><th>種類</th><td><%= p.type %></td></tr>
    <tr><th>送信者</th><td><%= p.sender %></td></tr>
    <tr><th>受信者</th><td><%= p.receiver %></td></tr>
    <tr><th>件名</th><td><%= p.subject %></td></tr>
    <tr><th>作成⽇時</th><td class="date"><%= p.created_at %></td></tr>
    <%# ¥ 2.ch.12.2.3 タグ付け - Tag-it インストール %>
    <tr>
      <th>タグ</th>
    <%# ¥ 2.ch.12.2.5 タグ付け - タグの追加・削除 %>
      <td>
        <%= markup(:ul, id: "tag-it", "data-message-id" => @message.id,
            "data-path" => staff_tag_message_path(id: @message.id)) do |m|
          @message.tags.each do |tag|
            m.li tag.value
          end
        end %>
      </td>
    </tr>
  </table>

  <%# ¥ 2.ch.11.2.2 ツリー構造 %>
  <div class="tree"><%= p.tree %></div>
  <div class="body"><%= p.formatted_body %></div>
</div>